---
- hosts: all
  vars_files:
      - secrets/{{ site }}-secrets.yml
  roles:
    - {role: dashenix , tags: [dashenix] }
    - {role: role-nodesntp , tags: [prerequis,ntpclient] }
    - {role: role-resolvconf , tags: [prerequis,resolvconf] }
    - {role: docker_install , tags: [prerequis,dockerinstall] }
    - {role: ansible-install , tags: [prerequis,ansibleinstall] }
